#!/bin/sh

# set root pointer
xsetroot -cursor_name left_ptr

#picom
pkill picom
picom -b &
#picom --expiremental-backends --no-use-damage &

# key bindings
sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

# panel
#tint2 &

# set some bsp specific
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config window_gap 6
bspc config border_width 2

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#other
systemctl start --now bluetooth
setxkbmap us -variant colemak
setxkbmap -option "caps:backspace"
setxkbmap -option "shift:both_capslock"
$HOME/.config/polybar/cuts/scripts/pywal.sh ~/wallpapers/aesthetic-mountains.jpeg
$HOME/.config/polybar/launch.sh --cuts
